<?php
public static $ALIGNMENT_ALIGNMENT_GENERAL = "general";
public static $ALIGNMENT_ALIGNMENT_CENTER = "center";
public static $ALIGNMENT_ALIGNMENT_LEFT = "left";
public static $ALIGNMENT_ALIGNMENT_RIGHT = "right";
public static $ALIGNMENT_ALIGNMENT_FILL = "fill";
public static $ALIGNMENT_ALIGNMENT_JUSTIFY = "justify";
public static $ALIGNMENT_ALIGNMENT_CENTER_ACROSS_SELECTION = "center across selection";
public static $ALIGNMENT_ALIGNMENT_DISTRIBUTED = "distributed";
public static $ALIGNMENT_ALIGNMENT_TOP = "top";
public static $ALIGNMENT_ALIGNMENT_MIDDLE = "middle";
public static $ALIGNMENT_ALIGNMENT_BOTTOM = "bottom";
public static $TEXT_DIRECTION_CONTEXT = 0;
public static $TEXT_DIRECTION_LEFT_TO_RIGHT = 1;
public static $TEXT_DIRECTION_RIGHT_TO_LEFT = 2;
?>
