<?php
public static $BORDER_BORDER_NONE = 0;
public static $BORDER_BORDER_THIN = 1;
public static $BORDER_BORDER_MEDIUM = 2;
public static $BORDER_BORDER_DASHED = 3;
public static $BORDER_BORDER_DOTTED = 4;
public static $BORDER_BORDER_THICK = 5;
public static $BORDER_BORDER_DOUBLE = 6;
public static $BORDER_BORDER_HAIR = 7;
public static $BORDER_BORDER_MEDIUM_DASHED = 8;
public static $BORDER_BORDER_DASH_DOT = 9;
public static $BORDER_BORDER_MEDIUM_DASH_DOT = 10;
public static $BORDER_BORDER_DASH_DOT_DOT = 11;
public static $BORDER_BORDER_MEDIUM_DASH_DOT_DOT = 12;
public static $BORDER_BORDER_SLANTED_DASH_DOT = 13;
?>
